version: '3'
services:
  db:
    image: influxdb:1.6-alpine
    ports: 
      - 8086:8086
    volumes:
      - ./tmp/influxdb:/var/lib/influxdb
  worker:
    build: .
    volumes:
      - .:/go/src/github.com/go-squads/floodgate-worker
    depends_on:
      - db
    env_file: .env
    links:
      - db
  chronograf:
    image: chronograf:1.6-alpine
    volumes:
      - ./tmp/chronograf:/var/lib/chronograf
    links:
      - db
    ports:
      - 8888:8888
